default[:wct][:image_dir] = "/tmp/was_suppl"
default[:wct][:image_file1] = "WAS_V8.5.5_SUPPL_1_OF_3.zip"
default[:wct][:image_file2] = "WAS_V8.5.5_SUPPL_2_OF_3.zip"
default[:wct][:image_file3] = "WAS_V8.5.5_SUPPL_3_OF_3.zip"
default[:wct][:install_dir] = "/opt/IBM/WebSphere/Toolbox"
default[:wct][:lang] = "ja"
default[:wct][:features] = "core.feature,pct,zpmt,zmmt"
